In [4]:
import numpy as np
from sklearn import preprocessing

In [5]:
data = np.array([[3, -1.5, 2, -5.4], [0, 4, -0.3, 2.1], [1, 3.3, -1.9, -4.3]])

In [6]:
data

array([[ 3. , -1.5,  2. , -5.4],
       [ 0. ,  4. , -0.3,  2.1],
       [ 1. ,  3.3, -1.9, -4.3]])

In [8]:
data_standardized = preprocessing.scale(data)
print("Mean : ", data_standardized.mean(axis = 0))
print("standard deviation : ", data_standardized.std(axis = 0))

Mean :  [ 5.55111512e-17 -1.11022302e-16 -7.40148683e-17 -7.40148683e-17]
standard deviation :  [1. 1. 1. 1.]


In [9]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(data)
print(data_scaled)

[[1.         0.         1.         0.        ]
 [0.         1.         0.41025641 1.        ]
 [0.33333333 0.87272727 0.         0.14666667]]


In [10]:
normal_data = preprocessing.normalize(data, "l1")
print(normal_data)

[[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


In [11]:
binarized_data = preprocessing.Binarizer(threshold=1.4).transform(data)
binarized_data

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 0.]])

In [13]:
encoder = preprocessing.OneHotEncoder()
encoder.fit([[0, 2, 1, 12], [1, 3, 5, 3], [2, 3, 2, 12], [1, 2, 4, 3]])
encoded_vector = encoder.transform([[2,3,5,3]]).toarray()
encoded_vector

array([[0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.]])

In [15]:
label_encoder = preprocessing.LabelEncoder()
data = ['audi', 'ford', 'audi', 'toyota', 'ford', 'bmw']
label_encoder.fit(data)
for i, item in enumerate(label_encoder.classes_):
    print(item," --> ",i)


audi  -->  0
bmw  -->  1
ford  -->  2
toyota  -->  3


In [16]:
labels = ['toyota', 'ford', 'audi']
label_encoded = label_encoder.transform(labels)
print(labels)
print(label_encoded)

['toyota', 'ford', 'audi']
[3 2 0]


In [20]:
label_encoded = [1,2,3,1,0]
label_decoded = label_encoder.inverse_transform(label_encoded)
print(label_decoded)
print(list(label_decoded))

['bmw' 'ford' 'toyota' 'bmw' 'audi']
['bmw', 'ford', 'toyota', 'bmw', 'audi']


In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("xlsxOperations.xlsx")
df

col1  col2
0    20    90
1    30    80
2    40    70
3    50    60

In [6]:
cols = ["col1","col2"]

df["Addition"] = df[cols[0]] + df[cols[1]]
df["Subtraction"] = df[cols[0]] - df[cols[1]]
df

col1  col2  Addition  Subtraction
0    20    90       110          -70
1    30    80       110          -50
2    40    70       110          -30
3    50    60       110          -10